# Generated by Django 3.2 on 2021-05-30 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_task_completed_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoricalattribute',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='numberattribute',
            name='dataset',
        ),
        migrations.DeleteModel(
            name='AttributeCategory',
        ),
        migrations.DeleteModel(
            name='CategoricalAttribute',
        ),
        migrations.DeleteModel(
            name='NumberAttribute',
        ),
    ]
